### ISSUE TITLE
Associated paper for academic citation?

### ISSUE THREAD

**Issue by cwpearson** [tbennun/mgbench#7]
I'd like to refer to this project in a paper I'm working on - is there a specific reference I should use?

**Comment by tbennun** [comment]
Thanks for contacting me.

Unfortunately, we did not publish a citable whitepaper for this project. You could provide the link to this repository as a citation. If you still wish to cite a paper, the closest publication you could use is the one describing the multi-GPU framework that powers the high-level tests: https://dl.acm.org/citation.cfm?id=2807611

**Comment by michaelsutton** [comment]
Some of the micro-benchmarks (L1) are reported here as well: https://dl.acm.org/citation.cfm?id=3018756 (Section 2.1) . 
Running scripts can be found here: https://github.com/groute/ppopp17-artifact/blob/master/figures/figure2.sh

**Comment by cwpearson** [comment]
Thank you, I'll cite the repository, and both of those papers look great too.

**Comment by tbennun** [comment]
Great, I'm closing this issue then.

**Comment by cwpearson** [comment]
@michaelsutton, sorry to revive this issue. In the paper you mentioned, what evaluation system was used to generate figure 2? Section 5 in the paper mentions 2 systems, I belive it is probably the system shown in figure 1. I'd be happy to converse over email if you prefer: pearson@illinois.edu. Thanks!

**Comment by michaelsutton** [comment]
@cwpearson, you are correct. The system used is the one in figure 1. The other node (heterogeneous 2-GPU) was only used for the results in Table 6.
