### ISSUE TITLE
Intel IOMMU

### ISSUE THREAD

**Issue by irishismyname** [tbennun/mgbench#8]
I'm not sure that this is actually an issue rather than a lack of awareness on my part, but I've observed the following:

After enabling Intel IOMMU in GRUB, benchmarking throws lots of errors during uva such as:

`DMAR: [DMA Write] Request Device [  :  :  .  ] fault addr`
`DMAR: [fault reason 05] PTE Write access is not set`

where `[  :  :  .  ]` and` fault addr` contain a variety of addresses.

**Comment by tbennun** [comment]
I'm not sure it's an issue with mgbench, it probably has to do with your hardware configuration. 

In any case, I've never seen this error, sorry.

**Comment by irishismyname** [comment]
Agreed. If you add intel_iommu=on as a kernel parameter, it will appear.
